# frozen_string_literal: true

require "bundler/setup"

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "rb_sys/extensiontask"

task build: :compile
task spec: :compile

gemspec = Gem::Specification.load("oxidizer.gemspec")

RbSys::ExtensionTask.new("oxidizer", gemspec) do |ext|
  ext.lib_dir = "lib/oxidizer"
  ext.cross_compile = true
end

task :clippy do
  sh "cargo clippy --features ext-magnus -- -D warnings"
end

require "yard"

YARD::Rake::YardocTask.new

task default: %i[compile spec clippy rubocop yard]
